// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package mysql

import (
	"context"
)

type Querier interface {
	ListBasTransations(ctx context.Context) ([]Bastransation, error)
}

var _ Querier = (*Queries)(nil)
