// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package mysql

import (
	"context"
)

const listBasTransations = `-- name: ListBasTransations :many
SELECT bas_transaction_id, name FROM BasTransation
`

func (q *Queries) ListBasTransations(ctx context.Context) ([]Bastransation, error) {
	rows, err := q.db.QueryContext(ctx, listBasTransations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bastransation
	for rows.Next() {
		var i Bastransation
		if err := rows.Scan(&i.BasTransactionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
